name: "Simplecov Report 2"
description: "Simplecov Report - A fork of Simplecov Report (aki77)"
author: lendkhoa
branding:
  icon: check-square
  color: green
inputs:
  failedThreshold:
    description: Failed threshold
    default: "90"
    required: false
  resultPath:
    description: "json path"
    default: "coverage/.last_run.json"
    required: false
  token:
    description: "Github token"
    required: true
runs:
  using: "node12"
  main: "dist/index.js"
